---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      serviceAccountName: {{ .Values.service_account }}
      securityContext:
        runAsUser: {{ .Values.podUserId }}
        runAsGroup: {{ .Values.podUserGid }}
      {{- include "logger.volume" .  | indent 6}}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.docker.image }}
        imagePullPolicy: Always
        securityContext:
          runAsUser: {{ .Values.containerUserId }}
          runAsGroup: {{ .Values.containerUserGid }}
          allowPrivilegeEscalation: false
        {{- include "logger.mount" .  | indent 8}}
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS 
          value: {{ .Values.gitRepo.searchFolders }}
        - name: ENCRYPT_KEY
          value: {{ .Values.encryptKey }}
        #- name: SPRING_CLOUD_CONFIG_OVERRIDENONE
        #  value: "true"
        #- name: SPRING_CLOUD_CONFIG_SERVER_OVERRIDES_SANDBOX_PUBLIC_URL
        #  value: {{ .Values.additionalParams.sandboxPublicUrl }}
        #- name: SPRING_CLOUD_CONFIG_SERVER_OVERRIDES_KEYCLOAK_EXTERNAL_URL
        #  value: {{ .Values.additionalParams.keycloakExternalUrl }}
        {{ if eq .Values.localRepo.enabled true }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: {{ .Values.localRepo.mountPath }}
        {{ else }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: {{ .Values.gitRepo.uri }}
        {{ if eq .Values.gitRepo.private true }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          value: {{ .Values.gitRepo.username }} 
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          value: {{ .Values.gitRepo.password }} 
        {{ end }} 
        {{ end }}
        ports:
        - containerPort: {{ .Values.docker.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
{{ if eq .Values.localRepo.enabled true }}
        volumeMounts:
        - name: repo
          mountPath: {{ .Values.localRepo.mountPath }} 
      volumes:
      - name: repo 
        persistentVolumeClaim:
          claimName: {{ .Values.localRepo.pvc.name }}
{{ end }}

