# DMZ cluster
- import_playbook: cluster.yml
  vars:
    cluster: dmzmaster dmzworkers
    master: dmzmaster.sb
    workers: dmzworkers
    cluster_name: dmzcluster  # Any string
    cluster_master: dmzmaster.sb  # Host name of master machine. e.g: mzmaster.sb
    console_kubeadmin_config_path: '{{clusters.dmz.kube_config}}'

# Ingress nginx controller
- import_playbook: ingress-nginx.yml
  vars:
    kube_config: '{{clusters.dmz.kube_config}}' 
    ingress_nginx_namespace: '{{clusters.dmz.ingress.namespace}}'

# Kubernetes dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.dmz.kube_config}}' 
    cluster_name: 'dmz'
    dashboard_conf: '{{clusters.dmz.dashboard}}'
  roles:
    - {role: k8scluster/dashboard}

# Load any secrets
- import_playbook: docker-secrets.yml
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'

#- import_playbook: create-namespace.yml
#  vars:
#    kube_config: '{{clusters.dmz.kube_config}}'