# MZ cluster
- import_playbook: cluster.yml
  vars:
    cluster: mzmaster mzworkers
    master: mzmaster.sb
    workers: mzworkers
    cluster_name: mzcluster  # Any string
    cluster_master: mzmaster.sb  # Host name of master machine. e.g: mzmaster.sb
    console_kubeadmin_config_path: '{{clusters.mz.kube_config}}'

# Ingress nginx controller
- import_playbook: ingress-nginx.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    ingress_nginx_namespace: '{{clusters.mz.ingress.namespace}}'

# Kubenetes dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    cluster_name: 'mz'
    dashboard_conf: '{{clusters.mz.dashboard}}'
  roles:
    - {role: k8scluster/dashboard}

# Load any secrets
- import_playbook: docker-secrets.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'

#- import_playbook: create-namespace.yml
#  vars:
#    kube_config: '{{clusters.mz.kube_config}}'
