---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{  .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.name }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      serviceAccountName: {{ .Values.service_account }}
      securityContext:
        runAsUser: {{ .Values.podUserId }}
        runAsGroup: {{ .Values.podUserGid }}
      {{- include "logger.volume" .  | indent 6}}
      containers:
      - name: {{  .Values.name }}
        image: {{ .Values.docker.image }}
        securityContext:
          runAsUser: {{ .Values.containerUserId }}
          runAsGroup: {{ .Values.containerUserGid }}
          allowPrivilegeEscalation: false
        {{- include "logger.mount" .  | indent 8}}
        ports:
        - containerPort: {{ .Values.docker.containerPort }}
        readinessProbe:
          tcpSocket:
            port: {{  .Values.docker.containerPort }}

