---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.service_account }}
      securityContext:
        runAsUser: {{ .Values.podUserId }}
        runAsGroup: {{ .Values.podUserGid }}
      {{- include "logger.volume" .  | indent 6}}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.dockerImage }}:{{ .Values.dockerTag }} 
        securityContext:
          runAsUser: {{ .Values.containerUserId }}
          runAsGroup: {{ .Values.containerUserGid }}
          allowPrivilegeEscalation: false
        {{- include "logger.mount" .  | indent 8}}
        env:
        - name: KEYCLOAK_USER 
          value: {{ .Values.keycloakUser }}
        - name: KEYCLOAK_PASSWORD 
          value: {{ .Values.keycloakPassword }}
        - name: DB_VENDOR 
          value: postgres
        - name: DB_ADDR
          value: {{ .Values.db.host }} 
        - name: DB_PORT
          value: "{{ .Values.db.port }}" 
        - name: DB_USER 
          value: {{ .Values.db.user }} 
        - name: DB_PASSWORD
          value: {{ .Values.db.password }} 
        - name: KEYCLOAK_FRONTEND_URL
          value: {{ .Values.keycloakExternalUrl }}  
        ports:
        - containerPort: {{ .Values.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}  # All defaults used

