apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.audit.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.audit.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.audit.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.audit.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      serviceAccountName: {{ .Values.service_account }}
      securityContext:
        runAsUser: {{ .Values.podUserId }}
        runAsGroup: {{ .Values.podUserGid }}
      {{- include "logger.volume" .  | indent 6}}
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.audit.serviceName }} 
        image: {{ .Values.services.audit.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ .Values.containerUserId }}
          runAsGroup: {{ .Values.containerUserGid }}
          allowPrivilegeEscalation: false
        {{- include "logger.mount" .  | indent 8}}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        ports:
        - containerPort: {{ .Values.services.audit.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.audit.healthUrl }} 
            port: {{ .Values.services.audit.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
   #     livenessProbe:
   #       httpGet:
   #         path: {{ .Values.services.audit.healthUrl }} 
   #         port: {{ .Values.services.audit.containerPort }} 
   #       initialDelaySeconds: {{ .Values.probe.initialDelay }} 
   #       periodSeconds: {{ .Values.probe.period }}
