#Create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account }}
  namespace: default
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
